services:
  cpa-helper:
    build: .
    image: cpa-helper:local
    container_name: cpa-helper
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "18317:18317"
    volumes:
      - ./data:/app/data